config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users 

  # default is set to index but if user is logged in, repective page will be rendered
  root to: "home#index"

  resources :patients, except: :edit
  get '/patients/:id/edit', to: 'patients#edit', as: 'edit_patient'
  
  delete '/patients/:id', to: 'patients#destroy', as: 'destroy_patient'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/doctor.rb
class Doctor < User
end

app/models/patient.rb
class Patient < ApplicationRecord
    # validates :name, :doctor_name, :appointment_date, :appointment_time, presence: true
  end
  

app/models/receptionist.rb
class Receptionist < User
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # adding extra attributes to user table
  attribute :type, :string
  attribute :username, :string


  # method doctor? checks if the user type is a doctor
  def doctor?
    type == "Doctor"
  end
  # method to checks if the user type is a receptionist
  def receptionist?
    type == "Receptionist"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    # permitting the extra attribute in devise signup form
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation, :type])
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

    if user_signed_in?
      if current_user.doctor?
        render 'doctor'
      elsif current_user.receptionist?
        @appointments = Patient.all
        render 'receptionist'
      end
    end
    
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
    def create
        @patient = Patient.new(patient_params)
      
        if @patient.save
          redirect_to root_path, notice: 'Appointment was successfully created.'
        else
          render :new
        end
    end

    def edit
        @appointment = Patient.find(params[:id])
    end

    def update
        @patient = Patient.find(params[:id])
    
        if @patient.update(patient_params_update)
          redirect_to root_path, notice: 'Appointment was successfully updated.'
        else
          render :edit
        end
    end

    def destroy
        @patient = Patient.find(params[:id])
        @patient.destroy
      
        redirect_to patients_path
    end
      
  
    private
  
    def patient_params_update
        params.require(:patient).permit(:name, :doctor_name, :appointment_date, :appointment_time)
    end

    def patient_params
        params.permit(:name, :doctor_name, :appointment_date, :appointment_time)
    end 
      
end  

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  # params.require(:user).permit(:email, :password, :password_confirmation, :type)

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/home/doctor.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doctor Page</title>
  </head>
  <body>
    <div class="container mt-5">
      <h1>Doctor Page</h1>
      <p>Welcome <%= current_user.username %>! Here you can view and manage your patients.</p>

      <div class="card mb-5">
        <div class="card-header">
          <h2>Appointments Today</h2>
        </div>
        <div class="card-body">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Name</th>
                <th>Doctor Name</th>
                <th>Date</th>
                <th>Time</th>
              </tr>
            </thead>
            <tbody>
              <% Patient.where(doctor_name: current_user.username, appointment_date: Date.today).each do |patient| %>
                <tr>
                  <td><%= patient.name %></td>
                  <td><%= patient.doctor_name %></td>
                  <td><%= patient.appointment_date %></td>
                  <td><%= patient.appointment_time.strftime('%I:%M %p') %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>

      <div class="card mb-5">
        <div class="card-header">
          <h2>All Active Appointments</h2>
        </div>
        <div class="card-body">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Name</th>
                <th>Doctor Name</th>
                <th>Date</th>
                <th>Time</th>
              </tr>
            </thead>
            <tbody>
              <% Patient.where(doctor_name: current_user.username).each do |patient| %>
                <tr>
                  <td><%= patient.name %></td>
                  <td><%= patient.doctor_name %></td>
                  <td><%= patient.appointment_date %></td>
                  <td><%= patient.appointment_time.strftime('%I:%M %p') %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>

      <div class="card">
        <div class="card-header">
          <h2>Patients vs Days Chart</h2>
        </div>
        <div class="card-body chart-container">
          <% data = {} %>
          <% (0..6).each do |n| %>
            <% date = Date.today + n.days %>
            <% count = Patient.where(doctor_name: current_user.username, appointment_date: date).count %>
            <% data["Day #{n+1}"] = count %>
          <% end %>
          <%= line_chart data %>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/home/index.html.erb
<div class="container my-5">
    <h1>Welcome to the Ruby On Rails Project!</h1>
    <p class="lead">This is a simple rails application that consists of a receptionist portal & a doctor portal which performs the following tasks:</p>
    <ul class="list-group">
        <li class="list-group-item">A single login page for both portals.</li>
        <li class="list-group-item">Receptionist can register a new patient & perform CRUD operations.</li>
        <li class="list-group-item">Doctor can view registered patient & view graph that represents patient registered vs days.</li>
    </ul>
    <p>Application uses PostgreSQL for the database and features proper Auth implementation using devise. We have also incorporated Bootstrap-Sass for styling and Chartkick gem for data visualization.</p>
    <p>Use Navbar for Signup/login</p>
</div>

app/views/home/receptionist.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Receptionist Page</title>
  </head>
  <body>

    <div class="container">
      <h1>Receptionist Page</h1>
      <p>Welcome <%= current_user.username %>! Here you can manage appointments, add patients, and more.</p>
      <div class="row">
        <div class="col-md-6">
          <h2>Add Appointments</h2>
          <%= form_with model: @patient, url: patients_path, local: true do |f| %>
            <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :doctor_name %>
              <%= f.collection_select :doctor_name, Doctor.all, :username, :username, { prompt: 'Select Doctor' }, { class: "form-control" } %>
            </div>
            <div class="form-group">
              <%= f.label :appointment_date %>
              <%= f.date_field :appointment_date, autocomplete: "appointment_date", class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :appointment_time %>
              <%= f.time_field :appointment_time, autocomplete: "appointment_time", class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.submit "Add Appointment", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
        <div class="col-md-6">
          <h2>View and Change Appointments</h2>
          <table class="table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Doctor Name</th>
                <th>Appointment Date</th>
                <th>Appointment Time</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @appointments.each do |appointment| %>
              <tr>
                <td><%= appointment.name %></td>
                <td><%= appointment.doctor_name %></td>
                <td><%= appointment.appointment_date %></td>
                <td><%= appointment.appointment_time.strftime('%I:%M %p') %></td>
                <td>
                  <%= button_to 'Update', edit_patient_path(appointment), method: :get, class: "btn btn-secondary" %>
                  <%= button_to 'Delete', patient_path(appointment), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger delete" %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/layouts/_navbar.html.erb
<%# navbar code %>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Medical Portal", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home" , root_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%# shows signout login etc links in the navbar according to user status%>
        <% if user_signed_in? %>
          <li><%= link_to "Edit Password", edit_user_registration_path %></li>
          <%# needed to use button here as link was unable to perform method: delete %>
          <li><%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn-link signout" %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MedicalPortal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/patients/edit.html.erb
<div class="container">    
    <%= form_with model: @appointment, url: patient_path(@appointment), method: :patch, local: true do |f| %>
    <div class="form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: "form-control", autofocus: true, autocomplete: "name" %>
    </div>

    <div class="form-group">
        <%= f.label :doctor_name %><br>
        <%= f.collection_select :doctor_name, Doctor.all, :username, :username, { prompt: 'Select Doctor' }, { class: "form-control" } %>
    </div>

    <div class="form-group">
        <%= f.label :appointment_date %><br>
        <%= f.date_field :appointment_date, class: "form-control", autocomplete: "appointment_date" %>
    </div>

    <div class="form-group">
        <%= f.label :appointment_time %><br>
        <%= f.time_field :appointment_time, class: "form-control", autocomplete: "appointment_time" %>
    </div>

    <div class="actions">
        <%= f.submit 'Update', class: "btn btn-primary" %>
    </div>
    <% end %>
</div>